"""Calibration constants for Nice."""

CALIBRATION_STORAGE_VERSION = 1
CALIBRATION_TARGETS = (20, 40, 60, 80)
CALIBRATION_SETTLE_SECONDS = 2.0
CALIBRATION_COMMAND_PAUSE_SECONDS = 0.5
CALIBRATION_SETTLE_TIMEOUT_SECONDS = 8.0
CALIBRATION_MOVEMENT_TIMEOUT_SECONDS = 90.0
CALIBRATION_ENDPOINT_TOLERANCE = 1.0
CALIBRATION_MAX_ATTEMPTS = 5
CALIBRATION_STABILITY_ATTEMPTS = 2
CALIBRATION_TARGET_TOLERANCE_PERCENT = 2.0
CALIBRATION_OUTLIER_ERROR_PERCENT = 15.0
CALIBRATION_REPORT_LOG_CHUNK_SIZE = 6000
CALIBRATION_STOPPED_ENDPOINT_GRACE_SECONDS = 3.0
CALIBRATION_STOPPED_ENDPOINT_MIN_DURATION_RATIO = 0.65
CALIBRATION_TIME_FULL_TRAVEL_ATTEMPTS = 3

CALIBRATION_STATE_CALIBRATED = "calibrated"
CALIBRATION_STATE_CANCELLED = "cancelled"
CALIBRATION_STATE_FAILED = "failed"
CALIBRATION_STATE_NOT_CALIBRATED = "not_calibrated"
CALIBRATION_STATE_RUNNING = "running"
